version: 2
jobs:
  build-linux:
    docker:
      - image: minextu/sdl2-cross-platform
    steps:
      - checkout
      - run: &init-steps
          name: Init
          command: |
            echo 'export EXECNAME=${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
            echo 'export BASENAME=${CIRCLE_PROJECT_REPONAME}-$(git describe --tags --always | sed -e 's/^v//')' >> $BASH_ENV
            mkdir artifacts
      - run:
          name: Build (Linux)
          command: make linux OUTPUT=${EXECNAME}
      - run:
          name: Store binary
          command: |
            zip -r artifacts/${BASENAME}-linux.zip ${EXECNAME} assets
            zip -j artifacts/${BASENAME}-linux.zip \
              LICENSE
            make -f Makefile.linux clean OUTPUT=${EXECNAME}
      - persist_to_workspace:
          root: .
          paths:
              - artifacts
  build-win:
    docker:
      - image: minextu/sdl2-cross-platform
    steps:
      - checkout
      - run: *init-steps
      - run:
          name: Build (Windows 32-bit)
          command: |
            PATH="/usr/i686-w64-mingw32/bin:$PATH"
            make linux CC=i686-w64-mingw32-g++ OUTPUT=${EXECNAME}.exe
      - run:
          name: Store binary
          command: |
            zip -r artifacts/${BASENAME}-win32.zip ${EXECNAME}.exe assets
            zip -j artifacts/${BASENAME}-win32.zip \
              LICENSE \
              /usr/i686-w64-mingw32/bin/SDL2.dll \
              /usr/i686-w64-mingw32/bin/SDL2_image.dll \
              /usr/i686-w64-mingw32/bin/libpng16-16.dll \
              /usr/i686-w64-mingw32/bin/zlib1.dll
            make -f Makefile.linux clean OUTPUT=${EXECNAME}.exe
      - persist_to_workspace:
          root: .
          paths:
              - artifacts
  build-macos:
    macos:
      xcode: 10.2.1
    steps:
      - checkout
      - run: *init-steps
      - restore_cache:
          keys:
            - brew-cache
      - run:
          name: Install deps
          command: brew install sdl2 sdl2_image zip
      - save_cache:
          key: brew-cache
          paths:
            - /usr/local/Homebrew
      - run:
          name: Build (MacOS)
          command: make macos
      - run:
          name: Store binary
          command: |
            zip -r artifacts/${BASENAME}-macos.zip ${EXECNAME} assets
            zip -j artifacts/${BASENAME}-macos.zip \
              LICENSE
      - persist_to_workspace:
          root: .
          paths:
              - artifacts
      - store_artifacts:
          path: ./artifacts
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git describe --tags --always)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} ${VERSION} ./artifacts/

workflows:
  version: 2
  test:
    jobs:
      - build-linux:
          filters: &build-filters
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - build-win:
          filters: *build-filters
      - build-macos:
          filters: *build-filters
  build-and-release:
    jobs:
      - build-linux:
          filters: &release-filters
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - build-win:
          filters: *release-filters
      - build-macos:
          filters: *release-filters
      - publish-github-release:
          requires:
            - build-linux
            - build-win
            - build-macos
          filters: *release-filters
